# http.host: "0.0.0.0"
# xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
# xpack.monitoring.elasticsearch.username: logstash_system
# xpack.monitoring.elasticsearch.password: changeme
# input:
#   udp:
#     host: "0.0.0.0"
#     port: 5228
#     codec: json_lines
# output:
#   elasticsearch:
#     hosts: ["elasticsearch:9200"]
#     codec: json_lines
#   stdout:
#     codec: json_lines

input {
  udp {
    host => "0.0.0.0"
    port => 5228
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    codec => json_lines
  }
  stdout {
    codec => json_lines
  }
}
