Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/amazon/product_advertising_api/parsers/item_lookup.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/amazon/product_advertising_api/parsers/item_lookup.rb'
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/migrate/*'
