Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
