version: '3'
services:
  web:
    ports:
      - "80:80"
    command: ./bin/rails s -p 80 -b '0.0.0.0'
    environment:
      RACK_ENV: production
      RAILS_ENV: production
      LANG: en_US.UTF-8
    restart: always

  database:
    volumes:
      - ./docker/database:/var/lib/postgresql/data
    restart: always

  redis:
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes # https://redis.io/topics/persistence
    restart: always

  sidekiq:
    restart: always

  elasticsearch:
    restart: always
