
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ./bin/rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - database
      - redis
      - elasticsearch
      - maildev
      - logstash
      # - sidekiq
  # sidekiq:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   command: sidekiq
  #   depends_on:
  #     - redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    volumes:
      - ./.logstash.yml:/usr/share/kibana/config/logstash.yml
    ports:
      - "5228:5228"
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
      - "5601:5601"
    volumes:
      - ./.kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
      - logstash
  database:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trackr_development
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
