version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ./bin/rails s -p 3000 -b '0.0.0.0'
    env_file: .env
    depends_on:
      - database
      - redis
      - maildev
      - sidekiq
      - elasticsearch

  database:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trackr_development

  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"

  sidekiq:
    build:
      context: .
    volumes:
      - .:/app
    env_file: .env
    command: sidekiq -c $RAILS_MAX_THREADS -q default -q mailers -q low_priority,1 -q high_priority,2
    depends_on:
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    volumes:
      - ./.elasticsearch.yml:/usr/share/kibana/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
